include("discrete_partitions.jl")
include("codon_models.jl")
include("GeneralCTMC.jl")
include("DiagonalizedCTMC.jl")
include("PiQ.jl")
include("interpolated_discrete_model.jl")
include("utils/utils.jl")
